name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm lint && pnpm typecheck

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        working-directory: ./server
        run: supabase start

      - name: Verify generated types are checked in
        working-directory: ./server
        run: |
          supabase gen types typescript --local --schema public > ../types/supabase.ts
          npx prettier --write ../types/supabase.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet ../types/supabase.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
